#!/usr/bin/env python3

# SPDX-PackageName: honestbt
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/honestbt
# SPDX-FileCopyrightText: © 2019 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

import argparse
import base64
import datetime
import mmap
import os
import random
import shlex
import sys

try:
    from Cryptodome.Cipher import AES
except ImportError:
    from Crypto.Cipher import AES

try:
    from Cryptodome.Util import Counter
except ImportError:
    from Crypto.Util import Counter

try:
    random_sys = random.SystemRandom()
except AttributeError:
    random_sys = random


class FileMmap:
    def __init__(self, filename, block_size=1048576):
        self.block_size = block_size
        flags = os.O_RDWR
        if hasattr(os, "O_DIRECT"):
            flags |= os.O_DIRECT
        if hasattr(os, "O_EXCL"):
            flags |= os.O_EXCL
        try:
            self.fileno = os.open(filename, flags)
        except OSError as e:
            if e.errno != 22:
                raise
            flags = os.O_RDWR
            self.fileno = os.open(filename, flags)
        self.file_size = os.lseek(self.fileno, 0, os.SEEK_END)
        os.lseek(self.fileno, 0, os.SEEK_SET)
        self.mmap = mmap.mmap(-1, block_size, flags=mmap.MAP_PRIVATE)

    def seek(self, pos, how=os.SEEK_SET):
        return os.lseek(self.fileno, pos, how)

    def write(self, data):
        if len(data) == self.block_size:
            self.mmap.seek(0)
            self.mmap.write(data)
            return os.writev(self.fileno, [self.mmap])
        else:
            mmap_temp = mmap.mmap(-1, len(data), flags=mmap.MAP_PRIVATE)
            mmap_temp.write(data)
            bytes_written = os.writev(self.fileno, [mmap_temp])
            mmap_temp.close()
            return bytes_written

    def read(self):
        self.mmap.seek(0)
        bytes_read = os.readv(self.fileno, [self.mmap])
        self.mmap.seek(0)
        return self.mmap.read(bytes_read)

    def flush(self):
        return os.fsync(self.fileno)


class HonestBT:
    f_clear = "\x1b[K"
    f_cr = "\r"
    is_tty = sys.stdout.isatty()

    def __init__(self):
        self.pos = 0
        self.written = 0
        self.tested = 0

    def parse_args(self, argv=None):
        if argv is None:
            argv = sys.argv

        arguments = {}

        def _add_argument(*args, **kwargs):
            if "tostr" in kwargs:
                tostr = kwargs["tostr"]
                del kwargs["tostr"]
            else:
                tostr = str
            argument = parser.add_argument(*args, **kwargs)
            argument.tostr = tostr
            arguments[argument.dest] = argument

        parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)

        # Positionals
        _add_argument("device", help="Device or file to destructively test")

        # Options
        _add_argument(
            "--key",
            type=base64.b64decode,
            default=base64.b64encode(bytes([random_sys.randint(0, 255) for _ in range(32)])).decode("UTF-8"),
            help="Base64-encoded 128/192/256 bit encryption key",
            tostr=lambda x: base64.b64encode(x).decode("UTF-8"),
        )
        _add_argument(
            "--fuzz",
            type=float,
            default="0.0",
            help="Percentage probability to modify each written byte",
        )
        _add_argument(
            "--begin",
            type=int,
            default="0",
            help="Zero-indexed byte to begin at within the device",
        )
        _add_argument(
            "--end",
            type=int,
            default="0",
            help="Zero-indexed byte to end at within the device (default last byte; device size minus 1 byte)",
        )
        _add_argument(
            "--block-size",
            type=int,
            default="1048576",
            help="I/O block size in bytes, must be multiple of device logical block size",
        )
        _add_argument("--resume-write", type=int, default="-1", help="Byte to resume write mode")
        _add_argument(
            "--resume-test",
            type=int,
            default="-1",
            help="Byte to resume test mode (skip write mode)",
        )
        _add_argument(
            "--fake-rollover",
            type=int,
            default="0",
            help="Beginning byte of simulated rollover device",
        )
        _add_argument(
            "--fake-zeroed",
            type=int,
            default="0",
            help="Beginning byte of simulated zeroed data",
        )
        _add_argument("--skip-test", action="store_true", help="Skip test entirely after write")

        args = parser.parse_args(args=argv[1:])
        args.parser = parser
        args.arguments = arguments

        if (len(args.key) * 8) not in (128, 192, 256):
            parser.error("Key must be 128, 192 or 256 bits")

        for dest in ("begin", "resume_write", "resume_test"):
            v = getattr(args, dest)
            if v == -1:
                continue
            if not (v / args.block_size).is_integer():
                parser.error(
                    "{}={} must be divisible by --block-size={}".format(arguments[dest].option_strings[0], v, args.block_size)
                )

        return args

    def strip_microseconds(self, td):
        return td - datetime.timedelta(microseconds=td.microseconds)

    def prettyb(self, number, mode=1000, precision=2):
        if mode == 1024:
            tags = ["", "Ki", "Mi", "Gi", "Ti"]
            divide = 1024
        else:
            tags = ["", "K", "M", "G", "T"]
            divide = 1000
        attag = 0
        while number >= divide:
            number = number / divide
            attag += 1
        return "{{:0.0{}f}} {{}}".format(precision).format(number, tags[attag])

    def print_resume(self, stage, retest=False):
        args = []
        required_dests = ["key"]
        for dest, argument in self.args.arguments.items():
            if dest in ("resume_write", "resume_test"):
                continue
            if dest == "skip_test" and stage == "test":
                continue
            v = getattr(self.args, dest)
            default_v = argument.default
            if argument.const is not None:
                if v != default_v:
                    args.append(argument.option_strings[0])
                continue
            v_str = argument.tostr(v)
            if default_v == v_str and dest not in required_dests:
                continue
            if len(argument.option_strings) == 0:
                args.append(v_str)
            else:
                args.append("{}={}".format(argument.option_strings[0], v_str))
        args.append("--resume-{}={}".format(stage, (0 if retest else self.pos)))
        print()
        if retest:
            print("To retest:")
        else:
            print("To resume:")
        print(
            "{} {}".format(
                shlex.quote(sys.argv[0]),
                " ".join([shlex.quote(x) for x in args]),
            )
        )

    def write_data(self):
        if self.args.resume_test >= 0:
            print("Skipping write")
            return

        print("Writing")

        self.pos = 0
        if self.args.begin:
            print("Beginning at {}B, as requested".format(self.prettyb(self.args.begin, 1024)))
            self.pos = self.args.begin
        if self.args.resume_write >= 0:
            print("Resuming write at {}B, as requested".format(self.prettyb(self.args.resume_write, 1024)))
            self.pos = self.args.resume_write
        self.fh.seek(self.pos)

        user_interrupted = None
        try:
            self.write_data_loop()
        except IOError as e:
            print()
            print(str(e))
            self.print_resume("write")
            raise
        except KeyboardInterrupt as e:
            user_interrupted = e
            print()

        print("Flushing")
        self.fh.flush()
        print("Successfully wrote {}B".format(self.prettyb(self.written, 1024)))
        if user_interrupted:
            self.print_resume("write")
            raise user_interrupted

    def write_data_loop(self):
        initial_value = int(self.pos / self.cipher_block_size)
        cipher = AES.new(
            self.args.key,
            AES.MODE_CTR,
            counter=Counter.new(128, initial_value=initial_value),
        )
        time_write_begin = datetime.datetime.now()
        pos_write_begin = self.pos
        time_last_print = time_write_begin
        pos_last_print = 0
        block_size = self.args.block_size
        zero_buf = bytes(block_size)

        sys.stdout.flush()
        while True:
            if (self.pos + self.args.block_size) > self.args.end:
                block_size = self.args.end - self.pos + 1
                zero_buf = bytes(block_size)
            encrypted = cipher.encrypt(zero_buf)

            if self.args.fuzz:
                encrypted = self.fuzz_data(encrypted)
            if self.args.fake_zeroed and self.pos >= (self.args.fake_zeroed + self.args.begin):
                encrypted = zero_buf
            if self.args.fake_rollover:
                self.fh.seek((self.args.begin + ((self.pos - self.args.begin) % self.args.fake_rollover)))

            self.fh.write(encrypted)
            self.written += block_size
            self.pos += block_size
            if self.pos >= self.args.end:
                break
            time_now = datetime.datetime.now()
            if time_now >= (time_last_print + datetime.timedelta(seconds=(1 if self.is_tty else 60))):
                estimated_end = time_write_begin + datetime.timedelta(
                    seconds=(time_now - time_write_begin).total_seconds() / (self.written / (self.args.end - pos_write_begin))
                )
                print(
                    "{}{}B written ({:.2%}), {}B/s, ~{} left ({} ETA){}".format(
                        (self.f_clear if self.is_tty else ""),
                        self.prettyb(self.written, 1024),
                        (self.pos - self.args.begin) / (self.args.end - self.args.begin),
                        self.prettyb(
                            (self.written - pos_last_print) / (time_now - time_last_print).total_seconds(),
                            1024,
                        ),
                        self.strip_microseconds(estimated_end - time_now),
                        estimated_end.strftime("%H:%M"),
                        (self.f_cr if self.is_tty else ""),
                    ),
                    end="",
                )
                sys.stdout.flush()
                time_last_print = time_now
                pos_last_print = self.written
        time_now = datetime.datetime.now()
        print(
            "{}{}B written, {}B/s in {}".format(
                (self.f_clear if self.is_tty else ""),
                self.prettyb(self.written, 1024),
                self.prettyb(self.written / (time_now - time_write_begin).total_seconds(), 1024),
                self.strip_microseconds(time_now - time_write_begin),
            )
        )

    def test_data(self):
        self.pos = 0

        if self.args.skip_test:
            print("Skipping test")
            self.print_resume("test")
            return

        print("Testing")

        if self.args.begin:
            print("Beginning at {}B, as requested".format(self.prettyb(self.args.begin, 1024)))
            self.pos = self.args.begin
        if self.args.resume_test >= 0:
            print("Resuming test at {}B, as requested".format(self.prettyb(self.args.resume_test, 1024)))
            self.pos = self.args.resume_test
        self.fh.seek(self.pos)

        try:
            self.test_data_loop()
        except IOError as e:
            print()
            print(str(e))
            self.print_resume("test")
            raise
        except KeyboardInterrupt:
            print()
            self.print_resume("test")
            raise
        self.print_resume("test", retest=True)

    def test_data_loop(self):
        initial_value = int(self.pos / self.cipher_block_size)
        cipher = AES.new(
            self.args.key,
            AES.MODE_CTR,
            counter=Counter.new(128, initial_value=initial_value),
        )
        time_test_begin = datetime.datetime.now()
        pos_test_begin = self.pos
        time_last_print = time_test_begin
        pos_last_print = 0
        block_size = self.args.block_size
        zero_buf = bytes(block_size)

        sys.stdout.flush()
        while True:
            if (self.pos + self.args.block_size) > self.args.end:
                block_size = self.args.end - self.pos + 1
                zero_buf = bytes(block_size)

            if self.args.fake_rollover:
                self.fh.seek((self.args.begin + ((self.pos - self.args.begin) % self.args.fake_rollover)))
            received = self.fh.read()
            encrypted = cipher.encrypt(zero_buf)

            if encrypted != received:
                for byte_pos in range(block_size):
                    if encrypted[byte_pos] != received[byte_pos]:
                        print(
                            "{} is bad: expected {:02x}, got {:02x}".format(
                                self.pos + byte_pos,
                                encrypted[byte_pos],
                                received[byte_pos],
                            )
                        )

            self.tested += block_size
            self.pos += block_size
            if self.pos >= self.args.end:
                break
            time_now = datetime.datetime.now()
            if time_now >= (time_last_print + datetime.timedelta(seconds=1)):
                estimated_end = time_test_begin + datetime.timedelta(
                    seconds=(time_now - time_test_begin).total_seconds() / (self.tested / (self.args.end - pos_test_begin))
                )
                print(
                    "{}{}B tested ({:.2%}), {}B/s, ~{} left ({} ETA){}".format(
                        (self.f_clear if self.is_tty else ""),
                        self.prettyb(self.tested, 1024),
                        (self.pos - self.args.begin) / (self.args.end - self.args.begin),
                        self.prettyb(
                            (self.tested - pos_last_print) / (time_now - time_last_print).total_seconds(),
                            1024,
                        ),
                        self.strip_microseconds(estimated_end - time_now),
                        estimated_end.strftime("%H:%M"),
                        (self.f_cr if self.is_tty else ""),
                    ),
                    end="",
                )
                sys.stdout.flush()
                time_last_print = time_now
                pos_last_print = self.tested
        time_now = datetime.datetime.now()
        print(
            "{}{}B tested, {}B/s in {}".format(
                (self.f_clear if self.is_tty else ""),
                self.prettyb(self.tested, 1024),
                self.prettyb(self.tested / (time_now - time_test_begin).total_seconds(), 1024),
                self.strip_microseconds(time_now - time_test_begin),
            )
        )

    def fuzz_data(self, data):
        pct_fraction = self.args.fuzz / 100.0
        data_bytearray = bytearray(data)
        for i in range(len(data)):
            if random.random() < pct_fraction:
                old_byte = data_bytearray[i]
                new_byte = random.randint(0, 255)
                print("FUZZ: Changing byte {} from {:02x} to {:02x}".format(self.pos + i, old_byte, new_byte))
                data_bytearray[i] = new_byte
        return bytes(data_bytearray)

    def main(self):
        self.args = self.parse_args()

        print("Testing {}".format(self.args.device))

        self.fh = FileMmap(self.args.device, self.args.block_size)

        if not self.args.end:
            self.args.end = self.fh.file_size - 1
        if self.args.end <= 0:
            self.args.parser.error("Cannot determine device size, specify --end of device size minus 1 byte")

        print("Key: {}".format(base64.b64encode(self.args.key).decode("UTF-8")))
        print("Block size: {}B ({})".format(self.prettyb(self.args.block_size, 1024), self.args.block_size))
        print("Begin: {}B ({})".format(self.prettyb(self.args.begin, 1024), self.args.begin))
        print("End: {}B ({})".format(self.prettyb(self.args.end, 1024), self.args.end))

        self.cipher_block_size = AES.new(self.args.key, AES.MODE_CTR, counter=Counter.new(128)).block_size

        try:
            self.write_data()
            self.test_data()
        except KeyboardInterrupt:
            return


if __name__ == "__main__":
    sys.exit(HonestBT().main())
